export enum RootStackName {
  Welcome = "Welcome",
  Login = "Login",
  Register = "Register",
  Home = "Home",
  ForgotPassword = "ForgotPassword",
  NewPassword = "NewPassword",
  Exercises = "Exercises",
  Profile = "Profile",
  Setting = "Setting",
  Nhap = "Nhap",
  Blog = "Blog",
  QuizGame = "QuizGame",
  PlayQuizGame = "PlayQuizGame",
  HowToPlayQuizGame = "HowToPlayQuizGame",
  DetailBlog = "DetailBlog",
  MiniTest = "MiniTest",
  Game2 = "Game2",
  TestHistory = "TestHistory",
  Result = "Result",
}