export enum RootStackName {
    Welcome = "Welcome",
    Login = "Login",
    Register = "Register",
    Home = "Home",
    ForgotPassword = "ForgotPassword",
    NewPassword = "NewPassword",
    Exercises = "Exercises",
    Profile = "Profile",
    Setting = "Setting",
    Nhap = "Nhap",
    Blog = "Blog",
    QuizGame = "QuizGame",
    DetailBlog = "DetailBlog",
    MiniTest = "MiniTest",
    HowPlay = "HowPlay",
    Game2 = "Game2",
    TestHistory = "TestHistory",
    Result = "Result",
  }