export * from './TestHistory'
export * from './exercises'
export * from './home'
export * from './login'
export * from './mini-test'
export * from './register'
export * from './result'
export * from './welcome'