export * from './test-history'
export * from './home'
export * from './login'
export * from './mini-tests'
export * from './welcome'
export * from './quiz-game'
export * from './reading-tips'
export * from './profile'